### ISSUE TITLE
Fix method and variable names

### ISSUE THREAD

**Issue by rajattrt** [LokeshLGJ/Birthday_Reminder_GUI#5]
https://github.com/LokeshLGJ/Birthday_Reminder_GUI/blob/9dabda9293ad800bae0287b34e000787b63758e4/Main_Birthday_Program.py#L14

Refer - https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables

**Comment by rajattrt** [comment]
https://github.com/LokeshLGJ/Birthday_Reminder_GUI/blob/master/Main_Birthday_Program.py#L11
https://github.com/LokeshLGJ/Birthday_Reminder_GUI/blob/master/Main_Birthday_Program.py#L12

Fix above variable names

**Comment by LokeshLGJ** [comment]
Done!!
