### ISSUE TITLE
Fix import order

### ISSUE THREAD

**Issue by rajattrt** [LokeshLGJ/Birthday_Reminder_GUI#6]
https://github.com/LokeshLGJ/Birthday_Reminder_GUI/blob/9dabda9293ad800bae0287b34e000787b63758e4/Main_Birthday_Program.py#L3

Imports should be grouped in the following order:
1. Standard library imports.
2. Related third party imports.
3. Local application/library specific imports.

Refer - https://www.python.org/dev/peps/pep-0008/#imports

**Comment by LokeshLGJ** [comment]
done
